
genre_dict = {
    "pop": 0,
    "dance pop": 0,
    "rap": 0,
    "rock": 0,
    "latin": 0,
    "hip hop": 0,
    "pop rap": 0,
    "trap": 0,
    "edm": 0,
    "metal": 0,
    "dance": 0,
    "wave": 0,
    "k-pop": 0,
    "j-pop": 0,
    "country": 0,
    "folk": 0,
    "punk": 0,
    "disco": 0,
    "singer-songwriter": 0,
    "funk": 0,
    "core": 0,
    "ambient": 0,
    "house": 0,
    "jazz": 0,
    "emo": 0,
    "chill": 0,
}

genre_mood_gen = {
        "pop": [
            "tacky",
            "thrilling",
            "easy",
            "suggestive",
            "cloying",
            "catchy",
            "upbeat",
            "mainstream",
        ],
        "dance pop": [
            "fabulous",
            "fast-paced",
            "danceable",
            "energetic",
            "bouncy",
            "energetic",
            "lively",
            "infectious",
        ],
        "rap": [
            "provocative",
            "thoughtful",
            "emotional",
            "powerful",
            "just",
            "rhyming",
            "expressive",
            "dynamic",
        ],
        "rock": [
            "old",
            "boring",
            "tasteless",
            "joy-sucking",
            "midwestern",
            "energetic",
            "powerful",
            "guitar-driven",
        ],
        "latin": [
            "rhythmic",
            "liquid",
            "viby",
            "bright",
            "stimulating",
            "rhythmic",
            "passionate",
            "colorful",
        ],
        "hip hop": [
            "poetic",
            "lively",
            "satisfying",
            "flowing",
            "organic",
            "urban",
            "rhythmic",
            "lyrical",
        ],
        "pop rap": [
            "quick",
            "sexual",
            "wealth-focused",
            "material",
            "synthetic",
            "catchy",
            "melodic",
            "upbeat",
        ],
        "trap": [
            "cash",
            "violence",
            "banger",
            "enveloping",
            "dominant",
            "heavy",
            "bass-driven",
            "dark",
        ],
        "edm": [
            "full",
            "veluptuous",
            "imaginary",
            "interminable",
            "drugs",
            "energetic",
            "upbeat",
            "electrifying",
        ],
        "metal": [
            "smelly",
            "textural",
            "imaginary",
            "sweaty",
            "explosive",
            "driving so fast",
            "heavy",
            "aggressive",
            "intense",
        ],
        "dance": [
            "smooth",
            "majestic",
            "pulsating",
            "magic",
            "energetic",
            "rhythmic",
            "groovy",
        ],
        "wave": [
            "pretentious",
            "incredulous",
            "lazing",
            "nostalgic",
            "chips ahoy commercial where they sang the human league",
            "haze",
            "new",
            "atmospheric",
            "dreamy",
            "melancholic",
        ],
        "k-pop": [
            "quick",
            "sumptuous",
            "presumptive",
            "engaging",
            "enticing",
            "upbeat",
            "addictive",
            "colorful",
        ],
        "j-pop": [
            "chill",
            "beachy",
            "fogged",
            "imposter",
            "magic",
            "melodic",
            "lively",
            "japanese",
        ],
        "country": [
            "pickup truck",
            "gothic",
            "19th century",
            "bloody",
            "varied",
            "melodic",
            "rooted",
            "storytelling",
        ],
        "folk": [
            "ancient",
            "personable",
            "honest",
            "intentional",
            "encumbent",
            "acoustic",
            "authentic",
            "cultural",
        ],
        "punk": [
            "powerful",
            "stripped down",
            "dishonest",
            "mislead",
            "engaged",
            "stinky",
            "rebellious",
            "raw",
            "fast-paced",
        ],
        "disco": [
            "shiny",
            "smooth",
            "rapturous",
            "healing",
            "hair flying",
            "sweat",
            "funky",
            "groovy",
            "retro",
        ],
        "singer-songwriter": [
            "personal",
            "poetic",
            "ascendant",
            "pontificate",
            "quietude",
            "poetic",
            "introspective",
            "melancholic",
        ],
        "funk": [
            "rhythmic",
            "unpredictable",
            "walking with a long unusual gait",
            "real type of thing",
            "motive",
            "groovy",
            "soulful",
            "rhythmic",
        ],
        "core": [
            "disimaginative",
            "progressive",
            "short feeling",
            "descriptive of a bad place",
            "bad time",
            "intense",
            "aggressive",
            "hard-hitting",
        ],
        "ambient": [
            "whispy",
            "airy",
            "timeless",
            "disengaged",
            "brian eno",
            "meditative",
            "soothing",
            "atmospheric",
        ],
        "house": [
            "full",
            "impressing",
            "pulling",
            "overwhelming",
            "bodily",
            "gay",
            "upbeat",
            "energetic",
            "clubby",
        ],
        "jazz": [
            "oceanic",
            "cathartic",
            "flowing",
            "infinite",
            "protection",
            "improvisational",
            "sophisticated",
            "swing",
        ],
        "emo": [
            "angst",
            "immaturity",
            "unaware",
            "pain",
            "grasping",
            "emotional",
            "melancholic",
            "expressive",
        ],
        "chill": [
            "peach",
            "clouded",
            "rain over dublin",
            "waiting",
            "dew",
            "relaxing",
            "mellow",
            "laid-back",
        ],
}

dic_list = {
    "pop": [],
    "dance pop": [],
    "rap": [],
    "rock": [],
    "latin": [],
    "hip hop": [],
    "pop rap": [],
    "trap": [],
    "edm": [],
    "metal": [],
    "dance": [],
    "wave": [],
    "k-pop": [],
    "j-pop": [],
    "country": [],
    "folk": [],
    "punk": [],
    "disco": [],
    "singer-songwriter": [],
    "funk": [],
    "core": [],
    "ambient": [],
    "house": [],
    "jazz": [],
    "emo": [],
    "chill": [],
}
